/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrmSentenciasControl;

import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author bradl
 */
public class Cadenas extends javax.swing.JFrame {

    /**
     * Creates new form Cadenas
     */
    public Cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bRealizar5 = new javax.swing.JButton();
        tfCadena = new javax.swing.JTextField();
        tfSubcadena2 = new javax.swing.JTextField();
        lEjer2 = new javax.swing.JLabel();
        lEjer6 = new javax.swing.JLabel();
        bRealizar2 = new javax.swing.JButton();
        tfSubcadena3 = new javax.swing.JTextField();
        lEjer3 = new javax.swing.JLabel();
        bRealizar6 = new javax.swing.JButton();
        bRealizar3 = new javax.swing.JButton();
        lInstruc1 = new javax.swing.JLabel();
        lEjer7 = new javax.swing.JLabel();
        lEjer4 = new javax.swing.JLabel();
        tfSubcadena4 = new javax.swing.JTextField();
        lEncabezado = new javax.swing.JLabel();
        tfSubcadena1 = new javax.swing.JTextField();
        bRealizar7 = new javax.swing.JButton();
        lInstruc = new javax.swing.JLabel();
        bRealizar4 = new javax.swing.JButton();
        lEjer1 = new javax.swing.JLabel();
        lEjer5 = new javax.swing.JLabel();
        bRealizar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bRealizar5.setText("Realizar");
        bRealizar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar5ActionPerformed(evt);
            }
        });

        tfCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCadenaActionPerformed(evt);
            }
        });

        lEjer2.setText("2. Imprima cada caracter de la cadena por separado");

        lEjer6.setText("6. Verifique si la siguiente cadena es mayor");

        bRealizar2.setText("Realizar");
        bRealizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar2ActionPerformed(evt);
            }
        });

        lEjer3.setText("3. Calcule la moda del caracter");

        bRealizar6.setText("Realizar");
        bRealizar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar6ActionPerformed(evt);
            }
        });

        bRealizar3.setText("Realizar");
        bRealizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar3ActionPerformed(evt);
            }
        });

        lInstruc1.setText("realice:");

        lEjer7.setText("7. Compare con la siguiente cadena");

        lEjer4.setText("4. Verifique si la siguiente subcadena existe");

        tfSubcadena4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubcadena4ActionPerformed(evt);
            }
        });

        lEncabezado.setText("La salida de cada operación deberá ser mostrada mediante cuadros de diálogo");

        bRealizar7.setText("Realizar");
        bRealizar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar7ActionPerformed(evt);
            }
        });

        lInstruc.setText("Con la cadena digitada a continuación");

        bRealizar4.setText("Realizar");
        bRealizar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar4ActionPerformed(evt);
            }
        });

        lEjer1.setText("1. Calcule su longitud");

        lEjer5.setText("5. Concatene la cadena dada con");

        bRealizar1.setText("Realizar");
        bRealizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEncabezado)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lInstruc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lInstruc1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lEjer1)
                        .addGap(3, 3, 3)
                        .addComponent(bRealizar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lEjer3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRealizar3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lEjer4)
                                .addGap(4, 4, 4)
                                .addComponent(tfSubcadena1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lEjer2)
                                .addGap(3, 3, 3)
                                .addComponent(bRealizar2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRealizar4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lEjer5)
                        .addGap(2, 2, 2)
                        .addComponent(tfSubcadena2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRealizar5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lEjer6)
                        .addGap(4, 4, 4)
                        .addComponent(tfSubcadena3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRealizar6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lEjer7)
                        .addGap(4, 4, 4)
                        .addComponent(tfSubcadena4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRealizar7)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEncabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lInstruc)
                    .addComponent(tfCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lInstruc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer1)
                    .addComponent(bRealizar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer2)
                    .addComponent(bRealizar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer3)
                    .addComponent(bRealizar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer4)
                    .addComponent(bRealizar4)
                    .addComponent(tfSubcadena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer5)
                    .addComponent(bRealizar5)
                    .addComponent(tfSubcadena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer6)
                    .addComponent(bRealizar6)
                    .addComponent(tfSubcadena3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer7)
                    .addComponent(bRealizar7)
                    .addComponent(tfSubcadena4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRealizar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar5ActionPerformed
        // TODO add your handling code here:
        String frase = tfCadena.getText();
        String frase2 = tfSubcadena2.getText();
        String fraseFinal = frase + frase2; 
        JOptionPane.showMessageDialog(null, fraseFinal);
    }//GEN-LAST:event_bRealizar5ActionPerformed

    private void tfCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCadenaActionPerformed

    private void bRealizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar2ActionPerformed
        // TODO add your handling code here:
        String frase = tfCadena.getText();
        
        for(int i = 0; i < frase.length(); i++){
            JOptionPane.showMessageDialog(null, frase.charAt(i));
        }
    }//GEN-LAST:event_bRealizar2ActionPerformed

    private void bRealizar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar6ActionPerformed
        // TODO add your handling code here:
        String frase = tfCadena.getText();
        String frase2 = tfSubcadena3.getText();
        if(frase.length() < frase2.length()){
            JOptionPane.showMessageDialog(null, "Esta frase es mayor");
        }else if(frase.length() == frase2.length()){
            JOptionPane.showMessageDialog(null, "Esta frase es del mismo tamaño");
        }else{
            JOptionPane.showMessageDialog(null, "Esta frase es menor");
        }
    }//GEN-LAST:event_bRealizar6ActionPerformed

    private void bRealizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar3ActionPerformed
        // TODO add your handling code here:
        String frase = tfCadena.getText();
        frase = frase.replace(" ", "");
        frase = frase.toLowerCase();
        char letras[] = frase.toCharArray();
        
        Map<Character, Integer> countMap = new HashMap();
        for (char letra : letras){
            try{
                countMap.put(letra,countMap.get(letra)+1);
            }catch(NullPointerException npe){
                countMap.put(letra, 1);
            }
        }
        char letraModa;
        letraModa = Collections.max(countMap.entrySet(), Comparator.comparingInt(Map.Entry::getValue)).getKey();
        JOptionPane.showMessageDialog(null,"La letra de moda en el texto ingresado es: " + letraModa + ", con una frecuencia de: " + countMap.get(letraModa));

        countMap.keySet().forEach((letra) -> {
        JOptionPane.showMessageDialog(null, "Letra [" + letra + "]: " + countMap.get(letra));
});
        
        
    }//GEN-LAST:event_bRealizar3ActionPerformed

    private void bRealizar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar7ActionPerformed
        // TODO add your handling code here:
        String frase = tfCadena.getText();
        String frase2 = tfSubcadena4.getText();
        if(frase.equals(frase2)){
            JOptionPane.showMessageDialog(null, "Son iguales");
        }else{
            JOptionPane.showMessageDialog(null, "Son diferentes");
        }
    }//GEN-LAST:event_bRealizar7ActionPerformed

    private void bRealizar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar4ActionPerformed
        // TODO add your handling code here:
        String sub = tfSubcadena1.getText();
        String frase = tfCadena.getText();
        if(frase.contains(sub))
        {
            JOptionPane.showMessageDialog(this, "Si la contiene");
        }else{
            JOptionPane.showMessageDialog(this, "No la contiene");
        }
    }//GEN-LAST:event_bRealizar4ActionPerformed

    private void bRealizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizar1ActionPerformed
        // TODO add your handling code here:
        String frase = tfCadena.getText();
        JOptionPane.showMessageDialog(this,frase.length() );
        
        
    }//GEN-LAST:event_bRealizar1ActionPerformed

    private void tfSubcadena4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubcadena4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSubcadena4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadenas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRealizar1;
    private javax.swing.JButton bRealizar2;
    private javax.swing.JButton bRealizar3;
    private javax.swing.JButton bRealizar30;
    private javax.swing.JButton bRealizar31;
    private javax.swing.JButton bRealizar4;
    private javax.swing.JButton bRealizar5;
    private javax.swing.JButton bRealizar6;
    private javax.swing.JButton bRealizar7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lEjer1;
    private javax.swing.JLabel lEjer2;
    private javax.swing.JLabel lEjer3;
    private javax.swing.JLabel lEjer4;
    private javax.swing.JLabel lEjer5;
    private javax.swing.JLabel lEjer6;
    private javax.swing.JLabel lEjer7;
    private javax.swing.JLabel lEncabezado;
    private javax.swing.JLabel lInstruc;
    private javax.swing.JLabel lInstruc1;
    private javax.swing.JTextField tfCadena;
    private javax.swing.JTextField tfSubcadena1;
    private javax.swing.JTextField tfSubcadena2;
    private javax.swing.JTextField tfSubcadena3;
    private javax.swing.JTextField tfSubcadena4;
    // End of variables declaration//GEN-END:variables
}
